; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed-xiao-esp32-c5]
platform = SeeedStudio
board = seeed-xiao-esp32-c5
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
monitor_speed = 115200
lib_deps = 
	moononournation/GFX Library for Arduino@^1.6.6
	bitbank2/PNGdec@^1.1.6
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	adafruit/Adafruit BusIO@^1.17.4
build_flags = 
	-D CONFIG_USB_CDC_ENABLED
	-D ARDUINO_USB_CDC_ON_BOOT=1
